"use client";

import { useState } from "react";
import { supabase } from "@/lib/supabase";

export default function AdminPage() {
  const [topic, setTopic] = useState("");
  const [loading, setLoading] = useState(false);

  async function generateArticle() {
    if (!topic) return;

    setLoading(true);

    const title = topic;
    const slug = topic.toLowerCase().replace(/\s+/g, "-");

    const desc =
      "AI generated investment article about " + topic;

    const content = `
${topic} is becoming one of the most discussed topics in modern investing.

Many investors believe that ${topic} could play an important role in long-term wealth building.

This article was automatically generated by AI.
`;

    const image =
      "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?q=80&w=1200";

    await supabase.from("articles").insert([
      {
        slug,
        title,
        desc,
        content,
        image,
      },
    ]);

    alert("Article created!");

    setTopic("");
    setLoading(false);
  }

  return (
    <div className="min-h-screen bg-black text-white p-10">
      <div className="max-w-2xl mx-auto">

        <h1 className="text-5xl font-bold text-amber-400">
          AI Article Generator
        </h1>

        <p className="mt-4 text-white/70">
          Generate investment articles using AI
        </p>

        <input
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          placeholder="Enter article topic..."
          className="w-full mt-10 p-4 rounded-xl bg-white/10 border border-white/10"
        />

        <button
          onClick={generateArticle}
          disabled={loading}
          className="mt-6 px-6 py-3 rounded-xl bg-amber-400 text-black font-bold"
        >
          {loading ? "Generating..." : "Generate Article"}
        </button>

      </div>
    </div>
  );
}
